const messages = {
  pt: {
    translations: {
      home: {
        titles: {
          section: 'Novidades',
        },
        messages: {
          bot: 'Este bot é capaz de te entregar resultados dos jogos de futebol ocorrendo no momento via WhatsApp por apenas R$0.99!',
          wip: 'DESCULPE, AINDA EM DESENVOLVIMENTO :(',
        },
      },
      privacyPolicy: {
        'Política de Privacidade': [
          { p: 'Atualizada pela última vez: 23 de Junho 2022' },
          {
            p: 'Esta Política de Privacidade descreve Nossas políticas e procedimentos sobre a coleta, uso e divulgação de Suas informações quando Você usa o Serviço e informa sobre Seus direitos de privacidade e como a lei protege Você.',
          },
          {
            p: 'Usamos seus dados pessoais para fornecer e melhorar o serviço. Ao utilizar o Serviço, você concorda com a coleta e uso das informações de acordo com esta Política de Privacidade. Esta Política de Privacidade foi criada com a ajuda do ',
          },
        ],
        'Interpretação e Definições': [
          { h2: 'Interpretação' },
          {
            p: 'As palavras cuja letra inicial é maiúscula têm significados definidos nas seguintes condições. As seguintes definições terão o mesmo significado, independentemente de aparecerem no singular ou no plural.',
          },
          { h2: 'Definições' },
          { p: 'Para os fins desta Política de Privacidade:' },
          {
            ul: [
              'Conta',
              ' significa uma conta exclusiva criada para você acessar nosso Serviço ou partes de nosso Serviço.',
              'Afiliado',
              ' significa uma entidade que controla, é controlada ou está sob controle comum com uma parte, onde "controle" significa propriedade de 50% ou mais das ações, participação acionária ou outros valores mobiliários com direito a voto para eleição de diretores ou outra autoridade administrativa.',
              'Aplicação',
              ' significa o programa de software fornecido pela Empresa baixado por Você em qualquer dispositivo eletrônico, denominado Zap Corporation',
              'Companhia',
              ' (referido como "a Empresa", "Nós", "Nós" ou "Nosso" neste Contrato) se refere à Zap Corporation.',
              'País',
              ' se refere ao: Brazil',
              'Dispositivo',
              ' significa qualquer dispositivo que possa acessar o Serviço, como um computador, um celular ou um tablet digital.',
              'Dados Pessoais',
              ' é qualquer informação relacionada a um indivíduo identificado ou identificável.',
              'Serviço',
              ' se refere a aplicação',
              'Fornecedor de Serviço',
              ' significa qualquer pessoa física ou jurídica que processe os dados em nome da Empresa. Refere-se a empresas terceirizadas ou indivíduos empregados pela Empresa para facilitar o Serviço, fornecer o Serviço em nome da Empresa, realizar serviços relacionados ao Serviço ou ajudar a Empresa a analisar como o Serviço é usado.',
              'Uso de Dados',
              ' refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
              'Você',
              ' significa o indivíduo acessando ou usando o serviço, ou a empresa ou outra entidade legal em nome do qual esse indivíduo está acessando ou usando o Serviço, conforme aplicável.',
            ],
          },
        ],
        'Coletando e usando seus dados pessoais': [
          { h2: 'Tipos de dados coletados' },
          { h3: 'Dados Pessoais' },
          {
            p: 'Ao usar nosso serviço, podemos solicitar que você nos forneça certas informações de identificação pessoal que podem ser usadas para entrar em contato ou identificá -lo. Informações pessoalmente identificáveis podem incluir, mas não se limitam a:',
          },
          { ul: ['Número de telefone', ' - Dados de uso'] },
          { h3: 'Dados de uso' },
          {
            p: 'Os dados de uso são coletados automaticamente ao usar o serviço.',
          },
          {
            p: 'Os dados de uso podem incluir informações como o endereço do protocolo da Internet do seu dispositivo (por exemplo, endereço IP), tipo de navegador, versão do navegador, as páginas do nosso serviço que você visita, a hora e a data da sua visita, o tempo gasto nas páginas, identificadores de dispositivo únicos e o diagnóstico de dados.',
          },
          {
            p: 'Quando você acessa o serviço por ou por meio de um dispositivo móvel, podemos coletar determinadas informações automaticamente, incluindo, entre outrosSistema operacional, o tipo de navegador da Internet móvel que você usa, identificadores de dispositivos exclusivos e outros dados de diagnóstico.',
          },
          {
            p: 'Também podemos coletar informações que seu navegador envia sempre que você visitar nosso serviço ou quando você acessa o serviço por ou por meio de um dispositivo móvel.',
          },
          { h2: 'Uso de seus dados pessoais' },
          {
            p: 'A empresa pode usar dados pessoais para os seguintes fins:',
          },
          {
            ul: [
              'Para fornecer e manter nosso serviço',
              ', inclusive para monitorar o uso do nosso serviço.',
              'Para gerenciar sua conta:',
              ' para gerenciar seu registro como usuário do serviço. Os dados pessoais que você fornece podem fornecer acesso a diferentes funcionalidades do serviço que estão disponíveis como usuário registrado. ',
              'Para o desempenho de um contrato:',
              ' O desenvolvimento, conformidade e empreendimento do contrato de compra para os produtos, itens ou serviços que você comprou ou de qualquer outro contrato conosco através do serviço.',
              'Para entrar em contato com você:',
              ' Para entrar em contato com você por e -mail, chamadas telefônicas, SMS ou outras formas equivalentes de comunicação eletrônica, como as notificações de push de um aplicativo móvel sobre atualizações ou comunicações informativas relacionadas às funcionalidades, produtos ou serviços contratados, incluindo as atualizações de segurança, quando necessário ou razoável para sua implementação.',
              'Para te prover',
              ' notícias, Ofertas especiais e informações gerais sobre outros bens, serviços e eventos que oferecemos que são semelhantes aos que você já comprou ou perguntou, a menos que tenha optado por não receber essas informações.',
              'Para gerenciar seus pedidos:',
              ' Para participar e gerenciar seus pedidos para nós.',
              'Para transferências de negócios:',
              ' Podemos usar suas informações para avaliar ou conduzir uma fusão, desinvestimento, reestruturação, reorganização, dissolução ou outra venda ou transferência de alguns ou de todos os nossos ativos, seja como uma preocupação em andamento ou como parte da falência, liquidação ou processo semelhante,,em que dados pessoais mantidos por nós sobre nossos usuários de serviço estão entre os ativos transferidos.',
              'Para outros propósitos',
              ': Podemos usar suas informações para outros fins, como análise de dados, identificar tendências de uso, determinar a eficácia de nossas campanhas promocionais e avaliar e melhorar nossos serviços, produtos, serviços, marketing e sua experiência.',
            ],
          },
          {
            p: 'Podemos compartilhar suas informações pessoais nas seguintes situações:',
          },
          {
            ul: [
              'Com prestadores de serviços:',
              ' Podemos compartilhar suas informações pessoais com os provedores de serviços para monitorar e analisar o uso de nosso serviço, para entrar em contato com você.',
              'Para transferências de negócios:',
              ' Podemos compartilhar ou transferir suas informações pessoais relacionadas a ou durante negociações de qualquer fusão, venda de ativos da empresa, financiamento ou aquisição de toda ou parte de nossos negócios para outra empresa.',
              'Com Afiliados:',
              ' Podemos compartilhar suas informações com nossas afiliadas; nesse caso, exigiremos que esses afiliados honrem essa Política de Privacidade. As afiliadas incluem nossa empresa controladora e quaisquer outras subsidiárias, parceiros de joint-venture ou outras empresas que controlamos ou que estejam sob controle comum conosco.',
              'Com parceiros de negócios:',
              ' Podemos compartilhar suas informações com nossos parceiros de negócios para oferecer determinados produtos, serviços ou promoções.',
              'Com outros usuários:',
              ' Quando você compartilha informações pessoais ou interage nas áreas públicas com outros usuários, essas informações podem ser visualizadas por todos os usuários e podem ser distribuídas publicamente fora.',
              'Com seu consentimento',
              ':Podemos divulgar suas informações pessoais para qualquer outro propósito com seu consentimento.',
            ],
          },
          { h2: 'Retenção de seus dados pessoais' },
          {
            p: 'A Companhia manterá seus dados pessoais apenas pelo tempo necessário para os fins estabelecidos nesta Política de Privacidade. Manteremos e usaremos seus dados pessoais na medida necessária para cumprir nossas obrigações legais (por exemplo, se formos obrigados a manter seus dados para cumprir as leis aplicáveis), resolver disputas e fazer cumprir nossos acordos e políticas legais.',
          },
          {
            P: 'A empresa também manterá dados de uso para fins de análise interna. Os dados de uso geralmente são retidos por um período mais curto, exceto quando esses dados são usados para fortalecer a segurança ou melhorar a funcionalidade de nosso serviço, ou somos legalmente obrigados a manter esses dados por períodos mais longos. ',
          },
          { h2: 'Transferência de seus dados pessoais' },
          {
            p: 'Suas informações, incluindo dados pessoais, são processadas nos escritórios operacionais da empresa e em outros locais onde estão localizadas as partes envolvidas no processamento. Isso significa que essas informações podem ser transferidas para - e mantidos em computadores localizados fora do seu estado, província, país ou outra jurisdição governamental, onde as leis de proteção de dados podem diferir do que as de sua jurisdição.',
          },
          {
            p: 'Seu consentimento para esta Política de Privacidade, seguida pelo seu envio de tais informações, representa seu contrato a essa transferência.',
          },
          {
            p: 'A Companhia tomará todas as etapas razoavelmente necessárias para garantir que seus dados sejam tratados com segurança e de acordo com esta Política de Privacidade e nenhuma transferência de seus dados pessoais ocorrerá para uma organização ou país, a menos que haja controles adequados, incluindo a segurança de seus dados e outras informações pessoais.',
          },
          { h2: 'Divulgação de seus dados pessoais' },
          { h3: 'Transações comerciais' },
          {
            p: 'Se a empresa estiver envolvida em uma fusão, aquisição ou venda de ativos, seus dados pessoais poderão ser transferidos. Forneceremos aviso prévio antes que seus dados pessoais sejam transferidos e fique sujeito a uma Política de Privacidade diferente.',
          },
          { h3: 'Aplicação da lei' },
          {
            p: 'Sob certas circunstâncias, a Companhia pode ser obrigada a divulgar seus dados pessoais, se necessário, por lei ou em resposta a solicitações válidas por autoridades públicas (por exemplo, um tribunal ou uma agência governamental).',
          },
          { h3: 'Outros requisitos legais' },
          {
            p: 'A empresa pode divulgar seus dados pessoais na crença de boa fé de que essa ação é necessária para:',
          },
          {
            ul: [
              '\n',
              'Cumprir uma obrigação legal',
              '\n',
              'Proteger e defender os direitos ou propriedade da empresa',
              '\n',
              'Prevenir ou investigar possíveis transgressões em conexão com o serviço',
              '\n',
              'Proteger a segurança pessoal dos usuários do serviço ou do público',
              '\n',
              'Proteger contra responsabilidade legal',
            ],
          },
          { h2: 'Segurança de seus dados pessoais' },
          {
            p: 'A segurança de seus dados pessoais é importante para nós, mas lembre -se de que nenhum método de transmissão pela Internet ou método de armazenamento eletrônico é 100% seguro. Embora nos esforcemos para usar meios comercialmente aceitáveis para proteger seus dados pessoais, não podemos garantir sua segurança absoluta.',
          },
        ],
        'Privacidade das crianças': [
          {
            p: 'Nosso serviço não aborda ninguém com menos de 13 anos. Não coletamos conscientemente informações de identificação pessoal de ninguém com menos de 13 anos. Se você é pai ou responsável e sabe que seu filho nos forneceu dados pessoais, por favor, por favorContate-Nos. Se percebermos que coletamos dados pessoais de qualquer pessoa com menos de 13 anos sem verificação do consentimento dos pais, tomamos medidas para remover essas informações de nossos servidores.',
          },
          {
            p: 'Se precisarmos confiar no consentimento como base legal para o processamento de suas informações e seu país exigir o consentimento dos pais, podemos exigir o consentimento de seus pais antes de coletar e usar essas informações.',
          },
        ],
        'Links para outros sites': [
          {
            p: 'Nosso serviço pode conter links para outros sites que não são operados por nós. Se você clicar em um link de terceiros, será direcionado para o site desse terceiro. Aconselhamos fortemente que você revise a Política de Privacidade de todos os sites que você visita.',
          },
          {
            p: 'Não temos controle e não assumimos nenhuma responsabilidade pelo conteúdo, políticas de privacidade ou práticas de sites ou serviços de terceiros.',
          },
        ],
        'Mudanças para esta Política de Privacidade': [
          {
            p: 'Podemos atualizar nossa Política de Privacidade de tempos em tempos. Notificaremos você sobre quaisquer alterações publicando a nova Política de Privacidade nesta página.',
          },
          {
            p: 'Avisaremos você por e -mail e/ou um aviso proeminente em nosso serviço, antes da alteração se tornar eficaz e atualizar a data "última atualizada" no topo desta Política de Privacidade.',
          },
          {
            p: 'Você é aconselhado a revisar essa Política de Privacidade periodicamente para quaisquer alterações. As alterações nessa Política de Privacidade são eficazes quando são publicadas nesta página.',
          },
        ],
        'Contate-nos': [
          {
            p: 'Se você tiver alguma dúvida sobre esta Política de Privacidade, entre em contato conosco:',
          },
          {
            ul: ['Por email: ', 'viniciusggrandi@gmail.com'],
          },
        ],
      },
      about: {
        title: 'Sobre',
        paragraphs: [
          'A Zap Corporation é uma empresa que fornece soluções digitais para empresas e organizações. Estamos comprometidos em fornecer os melhores produtos e serviços possíveis para nossos clientes, e estamos sempre nos esforçando para inovar e melhorar.',
          'Nossa equipe é composta por algumas das mentes mais brilhantes do negócio e estamos sempre procurando novas maneiras de inovar.',
          'Também estamos comprometidos em construir nossos produtos com responsabilidade, com segurança e ética em mente. Acreditamos que a tecnologia pode ser uma força para o bem, e estamos trabalhando para garantir que seja.',
        ]
      },
      footer: {
        first: 'Política de Privacidade',
        second: 'Sobre',
        part1: 'Desenvolvido por',
        part2: 'e design por',
      },
    },
  },
};

export { messages };
